# This YAML file contains the attacher & csi driver API objects that are necessary
# to run the external CSI attacher for nfusr

kind: Service
apiVersion: v1
metadata:
  name: csi-attacher-nfusrplugin
  labels:
    app: csi-attacher-nfusrplugin
spec:
  selector:
    app: csi-attacher-nfusrplugin
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-attacher-nfusrplugin
spec:
  serviceName: "csi-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-attacher-nfusrplugin
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-attacher
          image: docker.io/k8scsi/csi-attacher
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/

        - name: nfusr-csi
          image: quay.io/quamotion/nfusr-csi:latest:latest
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir:

