apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfusrplugin
  labels:
    name: data-nfusrplugin
  annotations:
    csi.volume.kubernetes.io/volume-attributes: '{"server": "cluster-storage", "share": "usbmuxd"}'
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  csi:
    driver: csi-nfusrplugin
    volumeHandle: data-id
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfusrplugin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["data-nfusrplugin"]
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: data-nfusrplugin 
  volumes:
  - name: data-nfusrplugin
    persistentVolumeClaim:
      claimName: data-nfusrplugin 
